
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS temp;
CREATE SCHEMA temp;
USE temp;

CREATE TABLE Product (
  ID VARCHAR(36) PRIMARY KEY ,
  Product_Name VARCHAR(100) NOT NULL,
  Product_Description TINYTEXT NOT NULL,
  Product_Price FLOAT NOT NULL,
  Product_Quantity INT NOT NULL,
  Product_Image TINYTEXT NOT NULL,
  -- Product_Ingredients TINYTEXT NOT NULL,
  CATEGORY_ID VARCHAR(36),
  BRAND_ID VARCHAR(36),
  SELLER_ID VARCHAR(36),
  FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID),
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
  FOREIGN KEY (SELLER_ID) REFERENCES SELLER(ID),
  Last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  
 -- KEY idx_actor_last_name (last_name)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;




